name: Node.js CD

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Build and Deploy to nCloud
    runs-on: ubuntu-latest
    env:
      client-directory: ./client
      server-directory: ./server
      CI: false
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x

      - name: Create client .env file
        working-directory: ${{env.client-directory}}
        run: |
          touch .env
          echo REACT_APP_S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}\ >> .env
          echo REACT_APP_S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}\ >> .env
          echo REACT_APP_S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}\ >> .env
          cat .env

      - name: Client npm install
        run: npm install
        working-directory: ${{env.client-directory}}

      - name: Client Build
        run: npm run build
        working-directory: ${{env.client-directory}}

      - name: Server npm install
        working-directory: ${{env.server-directory}}
        run: npm install

      - name: Create server .env file
        working-directory: ${{env.server-directory}}
        run: |
          touch .env
          echo DB_USER=${{ secrets.DB_USER }}\ >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }}\ >> .env
          echo SESSION_COOKIE_SECRET=${{ secrets.SESSION_COOKIE_SECRET }}\ >> .env
          cat .env

      - name: Server Build
        run: npm run build
        working-directory: ${{env.server-directory}}

      - name: clean-up deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT_DEV }}
          script: |
            rm -rf /usr/share/nginx/html/*
            cd duxcord 
            rm -rf *

      - name: copy client file to deploy server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT_DEV }}
          source: './client/build'
          target: '/usr/share/nginx/html'

      - name: copy server file to deploy server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT_DEV }}
          source: './server/dist'
          target: 'duxcord'

      - name: start app server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT_DEV }}
          script: |
            chown root duxcord/server
            cd duxcord/server/dist
            pm2 start main.js
            pm2 restart main.js
